npmPublishRegistry: "https://jfrogghdemo.jfrog.io/artifactory/api/npm/db-dependabot-local/"

npmRegistries:
  "https://jfrogghdemo.jfrog.io/artifactory/api/npm/db-dependabot-local/":
    npmAlwaysAuth: true
    npmAuthToken: ${secrets.JFROG_ARTIFACTORY_TOKEN}

npmRegistryServer: "https://jfrogghdemo.jfrog.io/artifactory/api/npm/db-dependabot-local/"

npmScopes:
  "":
    npmRegistryServer: "https://jfrogghdemo.jfrog.io/artifactory/api/npm/db-dependabot-local/"

compressionLevel: mixed
enableGlobalCache: false
nodeLinker: node-modules
yarnPath: .yarn/releases/yarn-4.3.1.cjs